name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, feature/ci_cd_added ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tidy (HTML validator)
        run: sudo apt-get update && sudo apt-get install -y tidy

      - name: Validate HTML files
        run: |
          for file in *.html; do
            tidy -errors -q $file
          done

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install stylelint
        run: npm install -g stylelint stylelint-config-standard

      - name: Validate CSS files
        run: |
          stylelint "assets/css/*.css" || true


  deploy:
    needs: lint
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build   # <-- dossier à publier
          publish_branch: gh-pages
